sitedesigns/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
from sitedesignsbase.views import index, contact, systaseis, works

urlpatterns = patterns('',
    url(r'^$',index,{'template_name': 'index.html'}),
    url(r'^contact/', contact, {'template_name': 'contact.html'}),
    url(r'^who_we_are/', systaseis, {'template_name': 'systaseis.html'}),
    url(r'^works/', works, {'template_name': 'works.html'}),
    url(r'^admin/', include(admin.site.urls))
)

sitedesignsbase/models.py
from django.db import models

class Story11(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	uptated_at = models.DateTimeField(auto_now=True)
	# text.allow_tags = True

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural = "Stories11"

sitedesigns/forms.py
# -*- coding: utf-8 -*-
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(label ='Όνομα')
    email = forms.EmailField()
    message = forms.CharField(widget = forms.Textarea(attrs={'cols':30, 'rows':7}), label ='Σχόλιο')

sitedesignsbase/views.py
from django.shortcuts import render
from django.template import Context
from models import Story11
from sitedesigns.forms import ContactForm
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

def index(request, template_name):
    s = Story11.objects.all()
    context = Context({'s':s, 'class':'' })
    return render(request, template_name, context)

def contact(request, template_name):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['sitedesigns17@gmail.com'],
            )
            return HttpResponseRedirect('/')
    else:
        form = ContactForm()
    s = Story11.objects.all()    
    context = Context({'s':s, 'form':form, 'class':'class="contact_emphasis"'})
    return render(request, template_name, context)

def systaseis(request, template_name):
    s = Story11.objects.all()
    context = Context({'s':s, 'class':'class="systaseis_emphasis"' })
    return render(request, template_name, context)


def works(request, template_name):
    s = Story11.objects.all()
    context = Context({'s':s, 'class':'class="works_emphasis"' })
    return render(request, template_name, context)

sitedesigns/templates/base.html
<!doctype html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="Σχεδιασμός σύγχρονων ιστοσελίδων.">
  <meta name="keywords" content="web, design, development,  responsive" >
  <meta name="author" content="Spyros D.C.>" >
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Site Designs</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600&subset=latin,greek' rel='stylesheet' type='text/css'>
  <link href="/static/images/favicon.ico" rel="icon" type="image/x-icon">
  <link href="/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <meta name="google-site-verification" content="iXpe3gA0EuULCTcSbbM8UrdYQ50VdZO7EauYBl_GaW0" >
  <link href="{{ STATIC_URL }}css/main.css" rel="stylesheet" type="text/css">
  <!--[if lt IE 9]>
     <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
     <script src="{{ STATIC_URL }}js/respond.min.js"></script>
  <![endif]-->
</head>
<body {{ class|safe }}>
  
  {% block header %}
  
  {% endblock %}

  <section id="content_one">
    
    {% block content_one %}

    {% endblock %}
    
  </section>
  <section id="content_two">
    
    {% block content_two %}

    {% endblock %}
    
  </section>
  <section id="content_three">
    
    {% block content_three %}

    {% endblock %}
    
  </section>
  <nav id="navigation_mobile">
    <ul id = "air_left">
      <li><a href="/contact/" class="contact" >Επικοινωνία</a></li>
      <li><a href="/who_we_are/" class="airleft who_we_are">Συστάσεις</a></li>
      <li><a href="/works/" class="works">Έργα</a></li>
    </ul>
  </nav>
  <footer id="footer">
    <div class="air_footer">
      <div class="left">
        <p>
          Designed by</br>Powered by Django
        </p>
      </div>
      <div class="left1">
        <img src="/static/images/logo-color1-small.gif">
      </div>
    </div>
  </footer>
<script src="{{ STATIC_URL }}js/firstscript.js"></script>
</body>
</html>

sitedesignsbase/templates/contact.html
{% extends "base.html" %}

{% block header %}

    <header id="header">
    <div class="logo"></div>
  
   <li><a href="/" class="absolute">Αρχική</a></li>
   </header>
   <nav id="navigation">
    <ul>
      <li><a href="/works/" class="works">Έργα</a></li>
      <li><a href="/contact/" class="contact">Επικοινωνία</a></li>
      <li><a href="/who_we_are/" class="airleft">Συστάσεις</a></li>
      <li><a href="/">Αρχική</a></li>
    </ul>
   </nav>     
 
{% endblock %}

{% block content_one %}

  
{% endblock %}

{% block content_two %}
<div>
  <h3 class="header_color">{{ s.2.title }}</h3>
  <p class="multi_colums">{{ s.2.text|safe }}</p>
</div>  
<div>
    <h2 class="header_color">Στείλτε μας ένα μήνυμα</h2>

   
       <div class="center_form">
           <form action="" method="post">{% csrf_token %}
              <div class="field">
                  <label for="id_subject"><p>Όνομα</p></label>
                  {{ form.subject.errors }}
                  {{ form.subject }}
              </div>
              <div class="field">
                  <label for="id_email"><p>E-mail</p></label>
                  {{ form.email.errors }}
                  {{ form.email }}
              </div>
              <div class="field">
                  <label for="id_message"><p>Σχόλιο</p></label>
                  {{ form.message.errors }}
                  {{ form.message }}
              </div>
              <div id="submit">
              <input type="submit" value="Αποστολή">
            </div>
          </form>
      </div>
</div>    
{% endblock %}      

sitedesignsbase/templates/index.html
{% extends "base.html" %}

{% block header %}
 <header id="header">
  <div class="logo"></div>
  
  <li><a href="#navigation_mobile" class="absolute">Menu</a></li>
  
 </header>
  <nav id="navigation">
    <ul>
      <li><a href="/works/" class="works">Έργα</a></li>
      <li><a href="/contact/" class="contact">Επικοινωνία</a></li>
      <li><a href="/who_we_are/" class="airleft">Συστάσεις</a></li>
    </ul>
  </nav>     
{% endblock %}

{% block content_one %}
  
  <div id="banner">
    <h2 class="main_color text_center">Σχεδιάζουμε σύγχρονες ιστοσελίδες</h2>
    <div class="tabs">
      <ul>
          <li><a href="#panel1" id="one">ΑΠΛΕΣ</a></li>
          <li><a href="#panel2" id="two">ΟΜΟΡΦΕΣ</a></li>
          <li><a href="#panel3" id="three">ΛΕΙΤΟΥΡΓΙΚΕΣ</a></li>
      </ul>
    </div>
  </div>

{% endblock %}

{% block content_two %}
  
  <div class="panel" id="panel1">
    <h3 class="header_color">{{ s.0.title }}</h3>
    <div class="multi_colums">{{ s.0.text|safe }}</div>   
    <div class="air">
      <img src="/static/images/google7.gif" class="center_tab">
    </div>
  </div>
  <div class="panel" id="panel2">
    <h3 class="header_color2">{{s.1.title}}</h3>
    <p class="multi_colums">{{s.1.text|safe}}</p>   
    <div class="air">
      <img src="/static/images/ZenGarden1.jpg" class="center_tab">
    </div>
  </div>
  <div class="panel" id="panel3">
    <h3 class="header_color3">{{s.4.title}}</h3>
    <p class="multi_colums">{{s.4.text|safe}}</p>   
    <div class="air">
      <img src="/static/images/responsive-design-hero.jpg" class="center_tab">
    </div>
  </div>

{% endblock %}

{% block content_three %}
  <h2 class="header_color">More about us</h2>
  <div class="cont_one">
    <p>
      <h3 class="header_color">{{s.5.title}}</h3>
      {{s.5.text|safe}}
    </p>
  </div>
  <div class="cont_two">
    <p>
      <h3 class="header_color">{{s.6.title}}</h3>
      {{s.6.text|safe}}
    </p>
  </div>

{% endblock %}

sitedesignsbase/templates/systaseis.html
{% extends "base.html" %}

{% block header %}

    <header id="header">
    <div class="logo"></div>
  
   <li><a href="/" class="absolute">Αρχική</a></li>
   </header>
   <nav id="navigation">
    <ul>
      <li><a href="/works/" class="works">Έργα</a></li>
      <li><a href="/contact/" class="contact">Επικοινωνία</a></li>
      <li><a href="/who_we_are/" class="airleft">Συστάσεις</a></li>
      <li><a href="/">Αρχική</a></li>
    </ul>
   </nav>     
 
{% endblock %}

{% block content_one %}
 
{% endblock %}

{% block content_two %}
<div>
  <h3 class="header_color">{{ s.3.title }}</h3>
  <div class="multi_colums">{{ s.3.text|safe }}</div>
</div>    
{% endblock %}      


sitedesignsbase/templates/works.html
{% extends "base.html" %}

{% block header %}

    <header id="header">
    <div class="logo"></div>
  
   <li><a href="/" class="absolute">Αρχική</a></li>
   </header>
   <nav id="navigation">
    <ul>
      <li><a href="/works/" class="works">Έργα</a></li>
      <li><a href="/contact/" class="contact">Επικοινωνία</a></li>
      <li><a href="/who_we_are/" class="airleft">Συστάσεις</a></li>
      <li><a href="/">Αρχική</a></li>
    </ul>
   </nav>     
 
{% endblock %}

{% block content_one %}
 
{% endblock %}

{% block content_two %}
<div class='tria'>

  <h3 class="header_color">Τα έργα μας</h3>
  <div class="ena">
    <a href="http://e-sfragida.gr" target="_blank"><img src="/static/images/e-sfragida.png"></a>
    <p>Ιστοσελίδα για παραγγελία-αγορά σφραγίδων.</p>
  </div>
 

  <div class="dio">
    <a href="http://e-xartopolio.gr" target="_blank"><img src="/static/images/e-xartopolio.png"></a>
    <p>Δυναμική ιστοσελίδα φτιαγμένη με WordPress.</p>
  </div>

   <div class="exi">
     <a href="http://englishbooks-thalassa.rhcloud.com/" target="_blank"><img src="/static/images/englishbooks-thalassa.png"></a>
     <p>Μία εφαρμογή βασισμένη σε node.js και mongo.db.</p>
  </div> 

  <div class="pente">
    <a href="http://sitedesigns.gr" target="_blank"><img src="/static/images/sd_favicon.png"></a>
    <p>Η δική μας ιστοσελίδα, φυσικά δυναμική με δικό μας σύστημα διαχείρισης περιεχομένου (CMS), βασισμένη στο django ένα web framework σε python.</p>
  </div> 

</div>   
{% endblock %}      
